#!/usr/bin/env bash
# The OSI model is a conceptual model that characterizes the communication functions of 
# a telecommunication system without regard to their underlying internal structure and technology
# The OSI model is organised from the lowest to the highest level
2
2
