#!/usr/bin/env bash
# get the IP from the command line using $*
# store the IP in a variable ip
# use if statement to check that ip isn't an empty string
# call ping command with ip variable - ping ip

ip=$*
if [ "$ip" == "" ];then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$ip"
fi
