#!/usr/bin/env bash
# copy contents of the hosts file to a new file hosts.new
# Use the sed command to find and replace some IP addresses in the host.new
# use cat to copy contents from ~/hosts.new to /etc/hosts

# using sed directly on docker will fail
# reason: Docker treats /etc/hosts differently. It overwrites it whenever it wants without any regard for your modifications

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
